### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by amiyasahu** [amiyasahu/Donut#52]
- [x] Full compatible for Q2A 1.7.4
- [x] Compress header image
- [x] Fix the tags overlapping issue
- [x] improve the drop down action items
- [x] Remove global reference for user levels
- [x] Improve the styling for the search panel
- [x] Improve posts moderation
- [x] Update for the ask box
- [x] top search button
- [x] improve the logic for home page check
- [x] Fix for category related links on profile page
- [x] Better search bar

**Comment by abuhasnatruhu** [comment]
Hello, please also add Open Login plugin issu for Facebook, google etc. I am not getting any user information using Open Login. PLease find the issue...

**Comment by amiyasahu** [comment]
![donut design](https://user-images.githubusercontent.com/2969035/44949562-470cf800-ae02-11e8-87cf-45072b4a88b1.png)

**Comment by amiyasahu** [comment]
Ignore this image, just added to use on Readme
